--- MCP 工具描述本地缓存（services.mcp.cache）专项测试
--- @module NeoAI.tests.test_mcp_cache
local tests = require("NeoAI.tests")

tests.suite("mcp_cache", function(_, it, before_each)
  local cache, path
  before_each(function()
    cache = require("NeoAI.services.mcp.cache")
    cache.reset()
    path = vim.fn.tempname() .. "-neoai_mcp_cache.json"
    cache.init(path)
  end)

  it("set/get/has：写入后可读回并报告存在", function(t)
    t.false_(cache.has("s1"), "初始不应有缓存")
    cache.set("s1", { tools = { { name = "t1" } } })
    local got = cache.get("s1")
    t.not_nil(got)
    t.eq("t1", got.tools[1].name)
    t.true_(cache.has("s1"), "有工具应报告存在")
    t.not_nil(got.updated_at, "应自动填充 updated_at")
  end)

  it("set：部分更新合并而非覆盖其他能力", function(t)
    cache.set("s1", { tools = { { name = "t1" } } })
    cache.set("s1", { resources = { { uri = "r1" } } })
    local got = cache.get("s1")
    t.eq("t1", got.tools[1].name, "旧 tools 应保留")
    t.eq("r1", got.resources[1].uri, "新 resources 应写入")
  end)

  it("update_all：整体覆盖并清除 pending/stale", function(t)
    cache.set("s1", { tools = { { name = "old" } } })
    cache.mark_pending("s1")
    cache.mark_stale("s1")
    cache.update_all("s1", { tools = { { name = "new" } }, resources = {}, prompts = {} })
    local got = cache.get("s1")
    t.eq("new", got.tools[1].name, "应整体覆盖")
    t.deep_eq({}, got.resources)
    t.false_(cache.is_pending("s1"), "update_all 应清除 pending")
    t.false_(cache.is_stale("s1"), "update_all 应清除 stale")
  end)

  it("pending：标记与查询", function(t)
    t.false_(cache.is_pending("s1"))
    cache.mark_pending("s1")
    t.true_(cache.is_pending("s1"))
  end)

  it("stale：标记、列举、清除", function(t)
    t.false_(cache.has_stale(), "初始无 stale")
    cache.mark_stale("a")
    cache.mark_stale("b")
    t.true_(cache.has_stale())
    t.true_(cache.is_stale("a"))
    local names = cache.stale_servers()
    table.sort(names)
    t.deep_eq({ "a", "b" }, names)
    cache.clear_stale("a")
    t.false_(cache.is_stale("a"))
    t.deep_eq({ "b" }, cache.stale_servers())
  end)

  it("持久化：重新 init 后从磁盘读回", function(t)
    cache.set("s1", { tools = { { name = "persisted" } } })
    cache.reset()
    cache.init(path)
    local got = cache.get("s1")
    t.not_nil(got)
    t.eq("persisted", got.tools[1].name)
  end)

  it("容错：损坏的缓存文件被忽略且不崩溃", function(t)
    local f = assert(io.open(path, "w"))
    f:write("not-json{{{")
    f:close()
    cache.reset()
    cache.init(path)
    t.nil_(cache.get("s1"), "损坏文件应被忽略")
    t.false_(cache.has("s1"))
  end)

  it("容错：缺失的字段被规范化为空表", function(t)
    local f = assert(io.open(path, "w"))
    f:write('{"servers":{"s1":{"tools":[{"name":"x"}]}}}')
    f:close()
    cache.reset()
    cache.init(path)
    t.true_(cache.has("s1"), "仅有 tools 也应存在")
    t.false_(cache.is_pending("s1"), "缺失 pending 应视为空")
    t.false_(cache.is_stale("s1"), "缺失 stale 应视为空")
  end)
end)
