--- 沙箱任务授权（grant）专项测试
--- @module 'NeoAI.tests.test_grant'
local tests = require("NeoAI.tests")

tests.suite("grant", function(_, it, before_each)
  local grant
  before_each(function()
    grant = require("NeoAI.sandbox.review.grant")
    grant.reset()
  end)

  it("创建：默认操作 fs_write、用量为 0、可按 id 查询", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant" } }, task_id = "task1", created_by = "user" })
    t.not_nil(g.grant_id)
    t.eq("task1", g.task_id)
    t.eq(0, g.usage.files)
    t.eq("user", g.created_by)
    t.deep_eq({ "fs_write" }, g.operations)
    t.eq(g, grant.get(g.grant_id), "get 应返回同一授权")
  end)

  it("scope：精确文件与目录前缀均覆盖", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant/exact.txt", "/tmp/neoai_grant/dir" } } })
    t.true_(grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/exact.txt" } } }), "精确文件应覆盖")
    t.true_(grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/dir/a/b.txt" } } }), "目录前缀应覆盖后代")
    local ok, reason = grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/other.txt" } } })
    t.false_(ok, "范围外路径不应覆盖")
    t.matches("PATH_OUTSIDE_GRANT_SCOPE", reason)
  end)

  it("scope：前缀不误伤同前缀兄弟路径", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant/dir" } } })
    t.false_(grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/dir2/x" } } }),
      "dir2 不应被 dir 前缀覆盖")
  end)

  it("scope：/** 递归匹配自身与后代", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant/sub/**" } } })
    t.true_(grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/sub" } } }), "应匹配目录自身")
    t.true_(grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/sub/deep/x" } } }), "应匹配后代")
    t.false_(grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/subx" } } }), "不应匹配同前缀兄弟")
  end)

  it("operations：未声明操作拒绝、* 通配放行", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant" } }, operations = { "fs_write" } })
    local ok, reason = grant.covers(g, "fs_delete", { files = {} })
    t.false_(ok)
    t.eq("GRANT_OPERATION_NOT_ALLOWED", reason)
    local w = grant.create({ scope = { paths = { "/tmp/neoai_grant" } }, operations = { "*" } })
    t.true_(grant.covers(w, "fs_delete", { files = {} }), "* 应放行任意操作")
  end)

  it("budget：累计用量超限后拒绝", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant" } }, budget = { max_files = 2 } })
    t.true_(grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/a" }, { path = "/tmp/neoai_grant/b" } } }))
    t.true_(grant.consume(g.grant_id, 2), "消费应成功")
    local ok, reason = grant.covers(g, "fs_write", { files = { { path = "/tmp/neoai_grant/c" } } })
    t.false_(ok, "超预算应拒绝")
    t.eq("GRANT_BUDGET_EXCEEDED", reason)
  end)

  it("有效期：ttl 过期后不活跃且不覆盖", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant" } }, ttl_sec = -1 })
    local ok, reason = grant.covers(g, "fs_write", { files = {} })
    t.false_(ok)
    t.eq("GRANT_INACTIVE", reason)
    t.eq(0, #grant.list({ active_only = true }), "过期授权不应出现在活跃列表")
  end)

  it("撤销：revoke 后不覆盖且不被 find_covering 命中", function(t)
    local g = grant.create({ scope = { paths = { "/tmp/neoai_grant" } } })
    t.true_(grant.revoke(g.grant_id))
    t.false_(grant.covers(g, "fs_write", { files = {} }))
    t.nil_(grant.find_covering("fs_write", { files = {} }))
    t.false_(grant.revoke("no_such_id"), "未知 id revoke 应返回 false")
  end)

  it("find_covering：命中活跃且范围匹配的授权", function(t)
    grant.create({ scope = { paths = { "/tmp/neoai_other" } } })
    local target = grant.create({ scope = { paths = { "/tmp/neoai_grant" } } })
    local found = grant.find_covering("fs_write", { files = { { path = "/tmp/neoai_grant/x" } } })
    t.not_nil(found)
    t.eq(target.grant_id, found.grant_id)
  end)

  it("list：active_only 过滤并按创建时间排序", function(t)
    local a = grant.create({ scope = { paths = { "/tmp/neoai_grant" } } })
    local b = grant.create({ scope = { paths = { "/tmp/neoai_grant" } } })
    a.created_at, b.created_at = 1, 2
    grant.revoke(b.grant_id)
    local active = grant.list({ active_only = true })
    t.eq(1, #active)
    t.eq(a.grant_id, active[1].grant_id)
    local all = grant.list()
    t.eq(2, #all)
    t.eq(a.grant_id, all[1].grant_id, "应按 created_at 升序")
    t.eq(b.grant_id, all[2].grant_id)
  end)
end)
