--- 模型注册表测试
--- @module NeoAI.tests.test_model_registry

local tests = require("NeoAI.tests")

tests.suite("model_registry", function(_, it)
  it("adapter 协议构造", function(t)
    local adapter = require("NeoAI.core.model.adapter")
    local a = adapter.get("openai")
    t.not_nil(a)
    t.eq("/chat/completions", a.chat_path())
    local body = a.build_body({ model = "m", messages = {}, stream = true, temperature = 0.5 })
    t.eq("m", body.model)
    t.true_(body.stream)
  end)

  it("openai 流式 chunk 解析", function(t)
    local adapter = require("NeoAI.core.model.adapter")
    local a = adapter.get("openai")
    local c = a.parse_stream_chunk('{"choices":[{"delta":{"content":"hi"},"finish_reason":null}]}')
    t.eq("hi", c.content)
    local c2 = a.parse_stream_chunk('{"choices":[{"delta":{"reasoning_content":"think"},"finish_reason":null}]}')
    t.eq("think", c2.reasoning)
    local done = a.parse_stream_chunk('{"choices":[{"delta":{},"finish_reason":"stop"}]}')
    t.eq("stop", done.finish_reason)
  end)

  it("openai 非流式响应解析", function(t)
    local adapter = require("NeoAI.core.model.adapter")
    local a = adapter.get("openai")
    local r = a.parse_response('{"choices":[{"message":{"content":"答","reasoning_content":"想"},"finish_reason":"stop"}],"usage":{"prompt_tokens":5}}')
    t.eq("答", r.content)
    t.eq("想", r.reasoning)
    t.eq(5, r.usage.prompt_tokens)
  end)

  it("openai /models 解析", function(t)
    local adapter = require("NeoAI.core.model.adapter")
    local a = adapter.get("openai")
    local models = a.parse_models('{"data":[{"id":"m1"},{"id":"m2"}]}')
    t.eq(2, #models)
    t.eq("m1", models[1].id)
    t.nil_(models[1].context_window)
    -- 兼容取 id 数组
    t.eq("m2", adapter.model_ids(models)[2])
  end)

  it("anthropic 协议解析", function(t)
    local adapter = require("NeoAI.core.model.adapter")
    local a = adapter.get("anthropic")
    t.not_nil(a)
    local r = a.parse_response('{"content":[{"type":"text","text":"答"}],"stop_reason":"end_turn"}')
    t.eq("答", r.content)
  end)

  it("google 协议解析", function(t)
    local adapter = require("NeoAI.core.model.adapter")
    local a = adapter.get("google")
    t.not_nil(a)
    local r = a.parse_response('{"candidates":[{"content":{"parts":[{"text":"答"}]},"finishReason":"STOP"}]}')
    t.eq("答", r.content)
  end)

  it("registry update + list + resolve_default", function(t)
    local config_store = require("NeoAI.kernel.config_store")
    config_store.load({ ai = { default_provider = "deepseek", default_model = "auto" } })
    local registry = require("NeoAI.core.model.registry")
    registry.reset()
    registry.update("deepseek", { "m1", "m2" })
    registry.list("deepseek"):then_(function(list)
      t.eq(2, #list)
      t.eq("m1", list[1].id)
      t.eq("available", list[1].status)
      t.eq("m1", registry.resolve_default("deepseek"))
      print("  registry list done")
    end)
  end)

  it("registry 空列表忽略", function(t)
    local registry = require("NeoAI.core.model.registry")
    registry.update("deepseek", { "m1" })
    registry.update("deepseek", {})
    registry.list("deepseek"):then_(function(list)
      t.eq(1, #list) -- 保留旧值
      print("  empty ignore done")
    end)
  end)

  it("registry subscribe 事件", function(t)
    local registry = require("NeoAI.core.model.registry")
    local async = require("NeoAI.utils.async")
    local received = nil
    local unsub = registry.subscribe(function(data) received = data end)
    registry.update("test_provider", { "x" })
    async.sleep(50):then_(function()
      t.not_nil(received)
      t.eq("test_provider", received.provider)
      unsub()
      print("  subscribe done")
    end)
  end)

  it("cache 读写 + 清空", function(t)
    local config_store = require("NeoAI.kernel.config_store")
    config_store.load({ ai = { model_refresh = { cache_path = "/tmp/neoai_test_models" } } })
    local cache = require("NeoAI.core.model.cache")
    cache.write("prov1", { "a", "b" })
    local data = cache.read("prov1")
    t.not_nil(data)
    t.eq(2, #data.models)
    t.true_(cache.is_fresh("prov1", 3600))
    cache.clear("prov1")
    t.nil_(cache.read("prov1"))
  end)

  it("fallback 模型", function(t)
    local adapter = require("NeoAI.core.model.adapter")
    local fb = adapter.get_fallback_models("openai")
    t.ok(#fb > 0)
    t.eq(0, #adapter.get_fallback_models("unknown_provider"))
  end)

  it("fetcher 失败回退到静态列表", function(t)
    local config_store = require("NeoAI.kernel.config_store")
    config_store.load({
      ai = {
        default_provider = "deepseek",
        providers = { deepseek = { api_type = "openai", base_url = "http://127.0.0.1:9999", api_key = "k", fetch_models = true } },
        model_refresh = { timeout_ms = 800 },
      },
    })
    local fetcher = require("NeoAI.core.model.fetcher")
    local async = require("NeoAI.utils.async")
    fetcher.fetch("deepseek"):then_(function(models)
      t.ok(#models > 0) -- 回退列表
      t.eq("deepseek-v4-flash", models[1])
      print("  fetch fallback done")
    end)
  end)
end)
